

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-techtrends-staging
  namespace: argocd
spec:

  project: default
  source:
    helm:
      valueFiles:
      - helm-techtrends-staging.yaml
    repoURL: https://github.com/cdpoboxhub/nd064_course_1.git
    path: project/argocd
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc


#    syncPolicy:
#      syncOptions:
##      - CreateNamespace = true
#
#      automated:
#        SelfHeal: true
#        prune: true
