namespace:
  name: prod 
 
service:
  port: 7111
  type: ClusterIP

image:
  repository: cdpoboxhub/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 5

resources:
  requests:
    cpu: 128m
    memory: 350Mi
  limits:
    cpu: 256m
    memory: 500Mi
    
configmap:
  data: "version: latest"
